### ISSUE TITLE
Spock and JUnit

### ISSUE THREAD

**Issue by 62Gerente** [62Gerente/BillMate#4]
Ricardo Branco @ricardobranco,

Estás a misturar spock com junit é suposto?

Ve isto:
http://www.christianoestreich.com/2012/11/domain-constraints-grails-spock-updated/
http://grails.org/doc/2.3.7/guide/testing.html

Principalmente o primeiro link, eu já tinha começado alguns testes e seguindo o primeiro link ficava melhor do que como tens. Só tem um pequeno problema, mas nos comentários está a solução.

Isto para testes unitários às constrains, depois para as relações é diferente, é com integration tests se não estou enganado. 

PS: Não dá para reduzir o nome desse branch? :japanese_ogre:

**Comment by ricardobranco** [comment]
eu tive a ver exemplos mias alguma documentação na net para ver se me
conseguia mexer
se é suposto nao sei

No dia 18 de Maio de 2014 às 14:07, André Augusto Costa Santos <
notifications@github.com> escreveu:

> Ricardo Branco @ricardobranco https://github.com/ricardobranco,
> 
> Estás a misturar spock com junit é suposto?
> 
> Ve isto:
> 
> http://www.christianoestreich.com/2012/11/domain-constraints-grails-spock-updated/
> http://grails.org/doc/2.3.7/guide/testing.html
> 
> Principalmente o primeiro link, eu já tinha começado alguns testes e
> seguindo o primeiro link ficava melhor do que como tens. Só tem um pequeno
> problema, mas nos comentários está a solução.
> 
> Isto para testes unitários às constrains, depois para as relações é
> diferente, é com integration tests se não estou enganado.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/62Gerente/BillMate/issues/4
> .

## 

Cumprimentos, Ricardo Branco

**Comment by 62Gerente** [comment]
Não é suposto, usa só spock.

Segue os exemplos que te enviei.
